#!/usr/bin/env python3
"""Materialize the exact reader-visible Pangram boundary from the R15 candidate."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


INTRODUCTION = "# Introduction"
PLACEHOLDER = re.compile(r"^\*\*\[EXISTING .+\]\*\*$")
MARKDOWN_LINK = re.compile(r"\[([^\]]+)\]\([^\n)]+\)")
HEADING_PREFIX = re.compile(r"^#{1,6}\s+")
LIST_PREFIX = re.compile(r"^(?:[-+*]|\d+\.)\s+")


def materialize(source: str) -> str:
    lines = source.splitlines()
    starts = [index for index, line in enumerate(lines) if line == INTRODUCTION]
    if len(starts) != 1:
        raise ValueError(f"expected one exact {INTRODUCTION!r} line, found {len(starts)}")

    placeholder_count = 0
    visible_lines: list[str] = []
    for raw_line in lines[starts[0] :]:
        line = raw_line.rstrip()
        if line == "---":
            continue
        if PLACEHOLDER.fullmatch(line):
            placeholder_count += 1
            continue

        line = HEADING_PREFIX.sub("", line)
        line = LIST_PREFIX.sub("", line)
        line = MARKDOWN_LINK.sub(r"\1", line)
        line = line.replace("**", "").replace("*", "")
        visible_lines.append(line)

    if placeholder_count != 7:
        raise ValueError(f"expected seven reader-visible native-object placeholders, found {placeholder_count}")

    boundary = "\n".join(visible_lines)
    # Historical whole-article GUI boundaries end with a final blank line.
    # Preserve that exact transport convention so the generated bytes can be
    # validated against an already-frozen known boundary.
    boundary = re.sub(r"\n{3,}", "\n\n", boundary).strip() + "\n\n"
    if "[EXISTING " in boundary or re.search(r"\[[^\]]+\]\([^\n)]+\)", boundary):
        raise ValueError("reader-visible boundary still contains excluded placeholder or Markdown link syntax")
    return boundary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    boundary = materialize(args.source.read_text(encoding="utf-8"))
    args.output.write_text(boundary, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
